const jCategory = [
    {
        index: 0,
        image : "../images/gogl.png",
        title: "Web Development",
        rate: "$900-$1200/m",
        av: "Full Time",
        companyName:"Google",
        location:"USA",
        vacancy:"01",
        hours:"50h/w",
        description:"A web developer is a technical professional who designs, builds, and maintains websites and web applications. They are responsible for ensuring a website is visually appealing, easy to navigate, and functions well. This involves writing code in various languages like HTML, CSS, and JavaScript to create the website's str ",
        workplace:"Work from Home",
        education:"Bachelor in computer Science Course.",
        experience:"2 t0 5 years"

    },
    {
        index: 1,
        image : "../images/uber.png",
        title: "Business Associate",
        rate: "$900-$1200/m",
        av: "Part Time",
        companyName: "Uber",
        location: "USA",
        vacancy: "04",
        hours:"40h / week",
        description:"Picking up and delivering customers. Taking the fastest and safest route. Helping to load and unload the vehicle. Calculating the right fare and returning the correct change.",
        workplace: "Work from office",
        education: "Driving Certificate",
        experience:"1 to 5 year(s)"
    },
    {
        index: 2,
        image : "../images/linked.png",
        title: "Business Associate",
        rate: "$900-$1200/m",
        av: "Part Time",
        companyName: "Uber",
        location: "UK",
        vacancy: "05",
        hours:"50h / week",
        description:"Picking up and delivering customers. Taking the fastest and safest route. Helping to load and unload the vehicle. Calculating the right fare and returning the correct change.",
        workplace: "Work from office",
        education: "Any Degree in Computer Science",
        experience:"1 to 3 year(s)"
    },
    {
        index: 3,
        image : "../images/faceboo.png",
        title: "Digital Marketing",
        rate: "$100-$1200/m",
        av: "Full Time",
        companyName: "Facebook",
        location: "USA",
        vacancy: "06",
        hours:"45h / week",
        description:"Picking up and delivering customers. Taking the fastest and safest route. Helping to load and unload the vehicle. Calculating the right fare and returning the correct change.",
        workplace: "Work from office",
        education: "Driving Certificate",
        experience:"1 to 5 year(s)"
    },
    {
        index: 4,
        image : "../images/yaho.jpeg",
        title: "User Experience",
        rate: "$800-$1100/m",
        av: "Part Time",
        companyName: "Uber",
        location: "USA",
        vacancy: "03",
        hours:"40h / week",
        description:"Picking up and delivering customers. Taking the fastest and safest route. Helping to load and unload the vehicle. Calculating the right fare and returning the correct change.",
        workplace: "Work from home",
        education: "Bachelor in information Technology",
        experience:"1 to 5 year(s)"
    },
    {
        index: 5,
        image : "../images/instagram.jpeg",
        title: "Product Designer",
        rate: "$900-$1200/m",
        av: "Full Time",
        companyName: "Instagram",
        location: "USA",
        vacancy: "05",
        hours:"50h / week",
        description:"the process of imagining, conceptualizing, testing, iterating and refining a product, service or experience so it's ready for its end user. Designers spend significant time on each of these steps, meaning that product design is a blend of research, strategy, industry knowledge and creative thinking.",
        workplace: "Work from office",
        education: "Any Degree related to Computer Science",
        experience:"2 to 4 year(s)"
    },
    {
        index: 6,
        image : "../images/freelancer.jpeg",
        title: "Product Manager",
        rate: "$900-$1100/m",
        av: "Part Time",
        companyName: "Freelancer",
        location: "Canada",
        vacancy: "02",
        hours:"45h / week",
        description:"the process of imagining, conceptualizing, testing, iterating and refining a product, service or experience so it's ready for its end user. Designers spend significant time on each of these steps, meaning that product design is a blend of research, strategy, industry knowledge and creative thinking.",
        workplace: "Work from home",
        education: "Degree in Computer Science course",
        experience:"1 to 4 year(s)"
    },
    {
        index: 5,
        image : "../images/apple.png",
        title: "Software Testing",
        rate: "$900-$1200/m",
        av: "Full Time",
        companyName: "Apple",
        location: "USA",
        vacancy: "03",
        hours:"50h / week",
        description:"evaluating a software product or application to ensure it functions correctly and meets user expectations. It involves identifying defects, errors, and bugs to improve the overall quality and reliability of the software.",
        workplace: "Work from office",
        education: "Any Degree related to Computer Science",
        experience:"0 to 2 year(s)"
    },
];